const tagList = [
  "DeFi",
  "NFTs",
  "Gaming",
  "Metaverse",
  "DAOs",
  "Privacy",
  "Security",
  "Regulation",
  "Sustainability",
  "Staking",
  "Yield Farming",
  "Layer 2",
  "Cross-chain",
  "Stablecoins",
  "Tokenomics",
  "Infrastructure",
  "Oracles",
  "AI & Blockchain",
  "Web3 Social",
  "Decentralized Identity",
  "Public Goods",
  "Grants & Funding",
  "Governance Efficiency",
  "Protocol Upgrades",
  "Risk Management",
  "Human Rights",
  "Ethics & Morality",
  "Democratic Participation",
  "Collective Decision-Making",
  "Voting Accessibility",
  "User Experience",
  "Economic Equality",
  "Behavioral Economics",
  "Community Engagement",
  "Bias & Fairness",
  "Transparency",
  "Reputation Systems",
  "Incentive Structures",
  "Free Speech",
  "Consensus Mechanisms",
  "Cognitive Bias",
  "Psychological Safety",
  "Identity & Anonymity",
  "Social Impact",
  "Moral Hazard",
  "Personalization & Autonomy",
  "Decentralized Ethics",
  "Trust & Credibility",
  "Philosophy of Governance",
  "Rights of Minority Groups",
];

export default tagList;
